[package]
name = "kale"
version = "0.1.0"
authors = ["Sunjay Varma <varma.sunjay@gmail.com>"]
edition = "2018"

[dependencies]
euc = "0.3"
lyon = "0.13"
vek = "0.9"

[dev-dependencies]
minifb = "0.11"

[profile.dev]
# Needed to make software rendering fast enough
opt-level = 3
